### ISSUE TITLE
Presentacion

### ISSUE THREAD

**Issue by ghost** [pdepviernestm/2024-presentacion-GeroBecker#1]
Buenas! . Muy buena preentacion gero , pero podrias adjuntar mas informacion acerca de tu familia asi sabemos un poco mas de vos (Hermana , padre , madre , etc...) . Saludos !

**Comment by GeroBecker** [comment]
Hola franco! Lo voy a tener en cuenta, en caso de querer saber mas de mi te puedo remitir al enlace de instagram en la presentacion, aunque quizas no encuentres la informacion que estas buscando, de todas formas muchas gracias!
