### ISSUE TITLE
Album favorito

### ISSUE THREAD

**Issue by Leo-de-Riv3r** [pdepviernestm/2024-presentacion-GeroBecker#3]
¿Cual es tu album favorito de Charly Garcia?

**Comment by GeroBecker** [comment]
Mi album favorito es Clics Modernos, es un album que no conoce los temas malos (en general Charly tampoco) y fue sin dudas un antes y un despues para Charly. Aun asi me gustaria agregar que ultimamente mis temas mas escuchados son de Parte De La Religion, Adela en el Carrousell es un temon.
